### ISSUE TITLE
There is no argument given that corresponds to the required parameter "y"

### ISSUE THREAD

**Issue by ajejdsn** [nifanfa/Cosmos-Draw-String#3]
When I trying to type this code: 
 canvas.DrawACSIIString("Hello World\n Test", 0, 0);
I have this:

![Знімок екрана 2024-04-07 162759](https://github.com/nifanfa/Cosmos-DrawString/assets/165407102/b0b73cca-a268-494d-a3f5-039348699cd2)

**Comment by nifanfa** [comment]
try
```cs
int x = 10;
int y = 10;
string content = "Hello World\n Test";
canvas.DrawACSIIString(Color.Red,content, x, y);
```

**Comment by ajejdsn** [comment]
Thank you, but I learned to draw string without any library, except System.Drawing and cosmos system lib
